name: CI

on:
  pull_request:
    branches:
      - dev

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Github Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
  Test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: swift build
      - name: Run unit tests
        run: swift test
